openapi: 3.0.0
info:
  title: Forum API
  description: Backend for creating SPA React Forum
  version: '1.0'
servers:
  - url: https://forum-api-jkrop.ondigitalocean.app
    description: Production environment
paths:
  /sandbox:
    post:
      summary: Creates a personal sandbox environment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:          # <!--- form field name
                  type: string
                ownerEmail:    # <!--- form field name
                  type: string
              required:
                - name
                - ownerEmail
              example:
                name: 'JontesAPI'
                email: 'jonatan.hallenberg@sprinto.se'
          
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string